name: Go CI
on:
  workflow_dispatch:
    inputs:
      from:
        description: "From"
        required: true
        default: "1001"
      to:
        description: "To"
        required: true
        default: "1001"
jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Go
        run: |
          npm install
          "node index.js ${{ github.event.inputs.from }} ${{ github.event.inputs.to }}"
